import Link from "next/link";
import { notFound } from "next/navigation";
import { getReport } from "@/lib/db";
import { formatDate } from "@/lib/format";
import { DownloadMarkdownButton } from "@/components/download-markdown-button";
import { KeyFindingsTable, MarkdownReport } from "@casky/ui-kit";
import type { KeyFinding, Severity } from "@casky/ui-kit";

const VALID_SEVERITIES: Severity[] = ["critical", "high", "medium", "low", "informational"];

export default async function ReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const report = await getReport(id);
  if (!report) notFound();

  // report_json is generated by harness.py's generate_consolidated_report()
  // (read directly, not assumed — see lib/types.ts's ConsolidatedReportJson
  // doc comment): { plan_id, domain, generated_at, steps_run, findings[],
  // summaries[] }. findings[] entries carry title/severity/description, so
  // they map onto ui-kit's KeyFinding type cleanly. There is NO structured
  // remediation-actions array (priority/effort/impact) in this shape — only
  // each finding's own free-text `remediation` field — so
  // ui-kit's RemediationTable does NOT apply here; we render each finding's
  // remediation text as a plain list instead of forcing a table shape that
  // doesn't exist in the data.
  const keyFindings: KeyFinding[] = (report.report_json?.findings ?? [])
    .filter((f) => f.title)
    .map((f) => ({
      title: f.title!,
      severity: (VALID_SEVERITIES.includes(f.severity as Severity)
        ? f.severity
        : "informational") as Severity,
      description: f.description ?? "",
    }));

  const remediationNotes = (report.report_json?.findings ?? []).filter((f) => f.remediation);

  return (
    <div className="max-w-4xl space-y-6">
      <div>
        <Link href="/reports" className="text-xs text-white/40 hover:text-white/70">
          ← Reports
        </Link>
        <div className="flex items-center justify-between gap-4 mt-2">
          <div>
            <h1 className="text-lg font-semibold text-[#EAF2FF]">
              {report.domain || report.investigation_id}
            </h1>
            <p className="text-xs text-white/35 mt-1">{formatDate(report.generated_at)}</p>
          </div>
          {report.markdown && (
            <DownloadMarkdownButton
              filename={`${(report.domain || report.investigation_id).replace(/\s+/g, "-")}-report.md`}
              markdown={report.markdown}
            />
          )}
        </div>
        <Link
          href={`/investigations/${report.investigation_id}`}
          className="text-xs text-white/35 hover:text-white/70 mt-1 inline-block"
        >
          View source investigation →
        </Link>
      </div>

      {report.summary && (
        <div className="rounded-xl p-4 bg-white/[0.03] border border-white/[0.07]">
          <h2 className="text-xs text-white/40 mb-2">Summary</h2>
          <p className="text-sm text-white/75 whitespace-pre-wrap">{report.summary}</p>
        </div>
      )}

      {keyFindings.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-white/60 mb-2">Key findings</h2>
          <KeyFindingsTable findings={keyFindings} />
        </div>
      )}

      {remediationNotes.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-white/60 mb-2">Remediation notes</h2>
          <p className="text-xs text-white/35 mb-2">
            report_json has no structured priority/effort/impact remediation table — each
            finding&apos;s own remediation text is listed here instead.
          </p>
          <ul className="space-y-2">
            {remediationNotes.map((f, i) => (
              <li
                key={i}
                className="rounded-lg p-3 bg-white/[0.03] border border-white/[0.06] text-sm text-white/70"
              >
                <span className="font-medium text-[#EAF2FF]">{f.title}: </span>
                {f.remediation}
              </li>
            ))}
          </ul>
        </div>
      )}

      {report.markdown && (
        <div>
          <h2 className="text-sm font-semibold text-white/60 mb-2">Full report</h2>
          <div className="rounded-xl p-5 bg-white/[0.03] border border-white/[0.07]">
            <MarkdownReport markdown={report.markdown} />
          </div>
        </div>
      )}
    </div>
  );
}
